### ISSUE TITLE
找不到problem.conf

### ISSUE THREAD

**Issue by W-X-Dai** [UniversalOJ/UOJ-System#107]
上傳檔案後系統顯示上傳成功，可是一它卻找不到problem.conf，後來跑去找了開源的測資資料夾上傳也一樣

**Comment by vfleaking** [comment]
感谢指出问题。可否提供一下更详细的信息呢？比如导致这个错误的具体操作步骤之类的

是否是按照这里的教程上传的呢：https://universaloj.github.io/post/%E4%BC%A0%E7%BB%9F%E9%A2%98%E9%85%8D%E7%BD%AE.html

或者试试这里的开源测资资料夹是否可以上传成功：
https://github.com/vfleaking/uoj-sample-problems

**Comment by W-X-Dai** [comment]
已經解決了，謝謝！
