### ISSUE TITLE
即使提交记录一般情况下只能查看自己的，但是指定用户之后仍然可以查看别人的。

### ISSUE THREAD

**Issue by HappyDavid3367** [UniversalOJ/UOJ-System#129]
如下。
![AE94E95D-8711-4BCF-BD62-AC252CAFDD5A](https://user-images.githubusercontent.com/102885358/228553952-aa9cca28-df63-4706-bc90-2bcdb4d785e3.png)
![57768E01-84B5-41CB-A0BA-42458D17DC33](https://user-images.githubusercontent.com/102885358/228553998-48cb3f72-b39f-4da3-8dbc-51474081a0ca.png)

**Comment by renbaoshuo** [comment]
此功能并非 UOJ 社区版中提供的功能，请联系贵校/机构的负责老师解决。
