### ISSUE TITLE
UOJForm的addVSelect无法对外来的选项显示错误信息

### ISSUE THREAD

**Issue by TRCYX** [UniversalOJ/UOJ-System#13]
例如在 `problem_data_manage.php` 中，有一个修改提交记录可视权限的 `view_type_form`。在浏览器里可以 F12 在里面加入新的 `<option>` 并提交，不会报错，结果会被加入 `extra_config`。（虽然这个值本身就可以在那个页面下面手写 `json` 改动）

虽然可以（似乎也应该）在 `handle` 里手动检测 `$_POST` 传入的值是不是可行的，但是希望 `addVSelect` 能够检查错误的选项

**Comment by billchenchina** [comment]
这个，，，貌似又是个大坑，，，

如果从 handle 改的话（貌似）所有和 UOJForm 有关的都需要改一遍 emmmm

**Comment by TechCiel** [comment]
如果其他的地方也这样的话，这很有可能引起严重的安全问题

**Comment by billchenchina** [comment]
看看 vfk 什么时候修吧 qaq

实在是无力。。

**Comment by TRCYX** [comment]
这个锅vfk修了。。是两个相当蠢的。。应该是typo吧
我弄了个pull request

**Comment by TRCYX** [comment]
其实也可以考虑把vfk最近做的一些commit弄过来
