### ISSUE TITLE
UOJ部署完成后有一个内置的root用户

### ISSUE THREAD

**Issue by fenychn0206** [UniversalOJ/UOJ-System#137]
不知为何按照指北部署完之后系统默认有一个root用户，相当于顶替掉了第一个注册用户的大管理权限，且不知道他的密码是多少

<img width="1059" alt="image" src="https://github.com/UniversalOJ/UOJ-System/assets/120368045/e4257c33-b79e-4de6-aed5-587db4529e54">

<img width="1088" alt="image" src="https://github.com/UniversalOJ/UOJ-System/assets/120368045/cc756f60-669c-4eef-819a-398e1a4b6247">

本站地址：http://154.3.2.170/

**Comment by fenychn0206** [comment]
@vfleaking 现在没有人能够打开大后台，因为有一个root账户在部署之后被自动创建

**Comment by renbaoshuo** [comment]
看起来这个像官网版？请麻烦确认一下是不是按照社区版搭建教程搭建的

**Comment by fenychn0206** [comment]
> 看起来这个像官网版？请麻烦确认一下是不是按照社区版搭建教程搭建的

是按照universaloj.github.io的教程搭建的

**Comment by renbaoshuo** [comment]
这个界面不像啊...

我更新了一下 https://universaloj.github.io/post/%E5%AE%89%E8%A3%85.html ，可以按照这个教程再安装一下试试。

**Comment by fenychn0206** [comment]
ok
