### ISSUE TITLE
How to change team members?

### ISSUE THREAD

**Issue by sleirsgoevy** [UniversalOJ/UOJ-System#146]
When I register on the official website (contest.ucup.ac) I can enter information (name, email, CodeForces nickname) about 3 team members. However when I click "edit profile" within the testing system, the form looks like it's made for individual contests (it contains one field "Real name", one field "Sex", etc.). Putting anything in the "Real name" field does not affect how the team is displayed. How can I edit team members?

EDIT. It seems that the open-source version of the platform only supports individual registration, and team registration is some local modification by the admins of contest.ucup.ac. However, I assume that they are the same people who are maintaining this repository, thus I'm reporting this here. Sorry if that's not actually the case.

**Comment by billchenchina** [comment]
No. We don't maintain contest.ucup.ac.
