### ISSUE TITLE
uoj-svn-lib不能阻止 非超级管理员 上传 非use_builtin_judger 的题目

### ISSUE THREAD

**Issue by TRCYX** [UniversalOJ/UOJ-System#15]
虽然这样其实好像挺好。。。不过在 [vfk 的文档](https://vfleaking.github.io/uoj/problem/) 下说的是只有超级管理员能这样做

在 `SvnSyncProblemDataHandler` 类的 `handle` 方法中有一个判断有没有 `use_builtin_judger` 的 `if`，其中 `else` 中会判断用户是不是超级管理员（`isSuperUser`），但是似乎有两个问题：

1. 条件写反了。理论上会变成只有超级管理员上传不了非 `use_builtin_judger` 的题目；
2. 在试图表示 `$this->user` 的时候写成了 `$user`，`NULL` 当然不 `isSuperUser` 啦。

所以结果就是所有题目管理员都能上传。可能会造成恶意的题目管理员在 `Makefile` 里面写上奇怪的东西的后果？

**Comment by MascoSkray** [comment]
上游更新的时候一并修掉了，那这个就关掉咯……
的确这个条件首先就少了一个'!'，然后条件就反掉了。
