### ISSUE TITLE
从修改个人信息登出后的页面无法登录

### ISSUE THREAD

**Issue by TRCYX** [UniversalOJ/UOJ-System#17]
在修改个人信息的页面登出会自动弹出登录页面，但没法登录进去

**Comment by MascoSkray** [comment]
原因是地址的传输保存和检测之间出了一些偏差，你在这个页面的每次登陆成功后会立即注销出去，然后返回的登陆界面登陆后依然会被注销。如此巡回往复。
当然其实这个问题解决办法最简单就是随便点到什么别的地方去再登录。当然既然你提出了这个问题那就动手把它修了吧 XD
