### ISSUE TITLE
希望内置Mathjax等库

### ISSUE THREAD

**Issue by chestnutprog** [UniversalOJ/UOJ-System#19]
由于需要断网比赛，在线的库无法使用

**Comment by naiij** [comment]
可以下载好到本地之后手动把cdn有关的几个替换掉，文件位置可以在[vfk那个repo](https://github.com/vfleaking/uoj)里面搜索。

**Comment by billchenchina** [comment]
由于 mathjax 太大了，我们不会把 mathjax 内置，请自行修改
