### ISSUE TITLE
直接使用docker pull弄下来的UOJ无法使用找回密码功能

### ISSUE THREAD

**Issue by AdemJensen** [UniversalOJ/UOJ-System#21]
如题，找回密码功能无法使用。访问forgotpw页面会导致500错误。

**Comment by AdemJensen** [comment]
如题，没有config.php导致的直接后果就是**找回密码功能**无法使用。

**Comment by billchenchina** [comment]
???

**Comment by billchenchina** [comment]
请问您 pull 的哪个分支？

**Comment by AdemJensen** [comment]
是根据部署指北使用的docker pull直接获取的docker镜像，不是pull的源代码。

**Comment by ghost** [comment]
请不要滥用assign功能 谢谢

**Comment by MascoSkray** [comment]
请参看 Commit 521b271
具体问题存在于forgot_pw.php的第23行和30行
由于变量名称又是下划线又是横杠的所以会出现语法错误
很早已经修正了

话说回来，这个stable已经很老了。
现在的php7分支已经可以算stable了，只是还没推到master分支
过一阵我会完成这个分支转换
