### ISSUE TITLE
uoj重启后题目乱码且无法创建题目和提交代码

### ISSUE THREAD

**Issue by ghost** [UniversalOJ/UOJ-System#26]
如题，使用的操作系统为Ubuntu 18.04（VMWare），且使用 [https://blog.csdn.net/tham_/article/details/73477255/](https://blog.csdn.net/tham_/article/details/73477255/) 和 [https://blog.csdn.net/tham_/article/details/73477255/](https://universaloj.github.io/)两个教程来部署uoj（主要是根据第一个教程添加了KodExplorer和phpMyAdmin，并且是直接用```apt install docker.io```安装的docker）
部署完成后一切运转正常，可以添加题目（没有乱码）。然而就在使用```docker restart uoj```重启后，所有重启前的题目的中文字乱码（变成了'？'），且新建题目、提交代码无效。目测是mysql出了问题，请问如何解决...

**Comment by earringyyr** [comment]
改几个文件夹的权限，那篇教程后面有

**Comment by ZGJackie** [comment]
> 
> 
> 改几个文件夹的权限，那篇教程后面有

emm...我试过了...这样会导致mysql重启失败，然后整个uoj都上不去了
请稍等一下，我发一个截图

**Comment by ZGJackie** [comment]
> 
> 
> 改几个文件夹的权限，那篇教程后面有

![错误截屏](https://user-images.githubusercontent.com/16496604/52159550-dfc0e000-26e0-11e9-887d-e661e80532fa.png)

**Comment by ghost** [comment]
又试了一遍，现在重启成功了，可是依然添加不了题目...（重启前貌似已经有题目了，是不是这个原因？）

**Comment by ghost** [comment]
![screenshot](https://user-images.githubusercontent.com/16496604/52159874-52cc5580-26e5-11e9-8ad6-dccd68291ee6.png)
二次重启mysql，结果又炸了..........

**Comment by MascoSkray** [comment]
您提供的教程链接提供的内容已经过时，因此可能不适应当前的情况。
我们无法确认您的具体操作，所以请尽可能的详细提供您的操作过程？
如果方便的话，您也可以根据UOJ部署指北首页的指示信息加群询问。

**Comment by MascoSkray** [comment]
另外此教程链接疑似内容转载。其中的内容可能发生更改。
请参阅 https://blog.csdn.net/rentenglong2012/article/details/70516285

**Comment by ghost** [comment]
十分感谢！我明天先试试这个博客，有问题再加群提问吧

**Comment by ghost** [comment]
已经解决了...修改文件夹权限时要把整个/etc/mysql都修改为755才可以。十分感谢！
