### ISSUE TITLE
Problem of the problem_id.zip

### ISSUE THREAD

**Issue by earringyyr** [UniversalOJ/UOJ-System#34]
The folder /var/uoj_data stores all the problems' data and it also have the compressed file for each problem. However, all the compressed files have a subfolder called /0. In this way, you can't upload the download file directly without deleting the subfolder /0. This really makes some problems for moving the problems from one UOJ to another UOJ.

**Comment by MascoSkray** [comment]
Maybe commit 2dc8e74 addressed this.
