### ISSUE TITLE
重启系统后提示错误

### ISSUE THREAD

**Issue by xyz60552** [UniversalOJ/UOJ-System#36]
网页显示database出现了错误.

**Comment by TRCYX** [comment]
试试看在docker里面 service mysql restart？

**Comment by billchenchina** [comment]
这个问题...貌似是广泛存在的...通常是 mysql 没启动成功...原因先🕊️着

**Comment by MascoSkray** [comment]
由于长时间没有回复，暂时做关闭处理。如有需要可以重开。
