### ISSUE TITLE
Current problem data upload system seems not supporting interactive problem.

### ISSUE THREAD

**Issue by C-SUNSHINE** [UniversalOJ/UOJ-System#49]
As mentioned in https://vfleaking.github.io/uoj/problem/ how we should configure an interactive, it is required to have a subdirectory "require" which contains "implementer.cpp" and other files needed when compiling.
However, svn has been removed and uploading with zip will drag all files in subdirectories to the root directory, which leads to an error failing to find require/implementer.cpp when compiling.

**Comment by MascoSkray** [comment]
Please check if commit bd74ed3 solves this problem.
