### ISSUE TITLE
/download.php?type=problem&id=1 404错误

### ISSUE THREAD

**Issue by Visors** [UniversalOJ/UOJ-System#50]
有看到uoj网站A+B问题
http://uoj.ac/download.php?type=problem&id=1
这个链接可以正常下载数据
但是自己测试添加测试问题后
http://xxx/download.php?type=problem&id=1
该链接打开为404错误
是需要额外配置什么吗？

**Comment by billchenchina** [comment]
需要自己在压缩包里将样例数据作为附加数据&样例数据
