### ISSUE TITLE
关于svn失效的问题

### ISSUE THREAD

**Issue by ZRZRING** [UniversalOJ/UOJ-System#59]
怎么更新网站的logo，还有怎么管理用户(比如删除用户)

**Comment by billchenchina** [comment]
svn 已经被移除了，如果需要更新 logo 的话请直接进入 docker 进行修改。

管理用户目前并没有实现，目前只能够修改用户组等。如有需要可以安一个 phpmyadmin。如果熟练 SQL 语句的话也可以进入 docker 后使用 MySQL CLI 进行管理。

**Comment by Ruanxingzhi** [comment]
uoj 没有预留删除用户的接口，不建议强行操作数据库。

案例：某 oj 强行删除用户之后，用户在博客评论区留下的讨论还在。
