### ISSUE TITLE
局域网访问题目有时会卡

### ISSUE THREAD

**Issue by ciao1** [UniversalOJ/UOJ-System#61]
自己用Ubuntu做了一台本地服务器，但是在局域网访问题目时有时会卡住，很慢。有时又很快，不知道什么原因

**Comment by billchenchina** [comment]
给出的信息不足以判断原因，有其他现象吗？

**Comment by ciao1** [comment]
其他现象也没有，就是进主页题库，点里面的某一题，进题目页面网页会等5s左右才页面刷出来。但有时候点一下就直接进题目页面了。

**Comment by ciao1** [comment]
问题初步解决，应该是局域网DNS的锅，配置了DNS点题就会卡。不配置就没有问题。
