### ISSUE TITLE
提交后无法查看详细结果/Unable to view detail result after submitting

### ISSUE THREAD

**Issue by Fish-lxy** [UniversalOJ/UOJ-System#79]
[提交结果后无法查看详细，点击分数后一片空白，
非满分和编译错误的提交无法看到结果，只能看见分数
此问题经常发生。
![after clicking score](https://user-images.githubusercontent.com/55318304/104465448-01c27d00-55ef-11eb-9c02-52067d3d802a.jpg)

**Comment by billchenchina** [comment]
这个应该是贵 OJ 管理员的限制，请咨询贵 OJ 管理员。
