### ISSUE TITLE
[BUG] 比赛名称含有字符 ' 会导致 rating 变化图无法显示

### ISSUE THREAD

**Issue by qz-cqy** [UniversalOJ/UOJ-System#88]
比赛名称含有字符 `'` （英文单引号）会导致 rating 变化图无法显示。

具体错误：

- 个人主页 rating 变化图无法显示。
- F12 控制台报出错误 `Uncaught SyntaxError: Invalid or unexpected token`。

复现方式：

- 创建一场 rated 比赛，名字为 `'`，或者名字中有单个的 `'`。
- 使用一个账号完成这场比赛。
- 赛后评测并公布成绩。
- 进入这个账号的个人主页，会出现上述错误。

**Comment by billchenchina** [comment]
感谢~
