### ISSUE TITLE
nginx反向代理无法使用https

### ISSUE THREAD

**Issue by MrThanlon** [UniversalOJ/UOJ-System#95]
RT，如果使用https，CSS等资源文件无法加载，因为他们的URL是http，被浏览器阻止了

**Comment by billchenchina** [comment]
.config.php 可以配置

**Comment by MrThanlon** [comment]
合理的方案不是应该自动判断吗？如果不打算强制使用https呢？内网使用http，公网使用https

**Comment by TechCiel** [comment]
@MrThanlon 你说的对，但是如果外网能够部署 TLS ，内网也应该尽量使用 TLS。。
