### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [UniversalOJ/UOJ-System#96]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by billchenchina** [comment]
Hi, the `SECURITY.md` has been [setup](https://github.com/UniversalOJ/UOJ-System/commit/9edd28541eb9fd8183179fa8a1a9363a0dcdf1cd). Please follow the security policy.

Thanks!

**Comment by billchenchina** [comment]
Hi, the security issue here is the same as https://github.com/vfleaking/uoj/issues/79. Should I take any action?
/cc @JamieSlome

**Comment by JamieSlome** [comment]
@billchenchina - apologies for the delay in response.

If you believe it to be a duplicate, feel free to mark the report as invalid.

Just (cc) in the researcher (@daffainfo).
