### ISSUE TITLE
Dockerfile builds the image using GitHub repo instead of local files

### ISSUE THREAD

**Issue by little-squirrel-cute** [UniversalOJ/UOJ-System#98]
The [docs](https://github.com/UniversalOJ/UniversalOJ.github.io/blob/c8edf7657d18b8471fa6462f9cfcb3c76399d2fe/post/%E6%9C%AC%E5%9C%B0%E6%9E%84%E5%BB%BA%E9%95%9C%E5%83%8F.md) said that the docker image could be built **locally** using these commands:

```bash
cd UOJ-System/install/bundle/
sudo docker build -t uoj-system .
```

But I've found that the `Dockerfile` used by the commands above builds the image using this GitHub repo instead of local files.

https://github.com/UniversalOJ/UOJ-System/blob/0d931e270b425b35fabb421ea21043ba2aaf9786/install/bundle/Dockerfile#L9

Is that behavior expected? If not, could you please fix them (e.g., by docker `COPY` command)?

Thanks!

**Comment by renbaoshuo** [comment]
fixed via https://github.com/UniversalOJ/UOJ-System/commit/436fa5f98fb96996ff51cd64de11e72c0bdc84b6
